apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.0.0
    helm:
      values: |
        grafana:
          enable: true
        write:
          persistence:
            storageClass: bsu-sc
        backend:
          persistence:
            storageClass: bsu-sc
        read:
          persistencce:
            storageClass: bsu-sc
        singleBinary:
          persistence:
            storageClass: bsu-sc
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true